#!/usr/bin/env python3
"""Fleet inventory view generator.

Parses the control-plane allow-list (``jolarca-control/repos/*.yml``) and renders
``inventory/fleet.md`` — a read-only **view**. The allow-list remains the ISO 27001
A.5.9 system of record (ADR DOC-0001); this view exists so the fleet has one
accurate, generated inventory and so ``scripts/verify.py`` can machine-catch the
count drift recorded as finding F-DOC-03.

Fail loud, never degrade: a missing allow-list is a hard failure under ``--strict``
and stamps a PARTIAL banner otherwise; zero entries is always a failure.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
FLEET_ROOT = REPO_ROOT.parent
CONTROL_REPOS = FLEET_ROOT / "jolarca-control" / "repos"
OUTPUT_MD = REPO_ROOT / "inventory" / "fleet.md"


@dataclass(frozen=True)
class RepoEntry:
    name: str
    tier: str
    criticality: str
    launch_status: str
    visibility: str
    data_classification: str
    frameworks: str


def _text(data: dict[str, Any], key: str, default: str = "—") -> str:
    value = data.get(key)
    return str(value) if value not in (None, "") else default


def _nested(data: dict[str, Any], *path: str) -> Any:
    node: Any = data
    for key in path:
        if not isinstance(node, dict):
            return None
        node = node.get(key)
    return node


def load_allowlist(control_repos: Path) -> list[RepoEntry]:
    entries: list[RepoEntry] = []
    for path in sorted(control_repos.glob("*.yml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(f"{path.name}: allow-list entry is not a mapping")
        raw: dict[str, Any] = data
        frameworks = _nested(raw, "compliance", "frameworks") or []
        if not isinstance(frameworks, list):
            raise ValueError(f"{path.name}: compliance.frameworks is not a list")
        classification = _nested(raw, "compliance", "data_classification")
        entries.append(
            RepoEntry(
                name=_text(raw, "name", path.stem),
                tier=_text(raw, "tier"),
                criticality=_text(raw, "criticality"),
                launch_status=_text(raw, "launch_status"),
                visibility=_text(raw, "visibility"),
                data_classification=str(classification)
                if classification not in (None, "")
                else _text(raw, "data_classification"),
                frameworks=", ".join(str(f) for f in sorted(frameworks)) or "—",
            )
        )
    return entries


def render(entries: list[RepoEntry], *, partial: bool) -> str:
    lines: list[str] = [
        "<!-- GENERATED by scripts/build_inventory.py — DO NOT EDIT. The allow-list",
        "     (jolarca-control/repos/*.yml) is the system of record; this is a view. -->",
        "# Fleet Inventory (generated view)",
        "",
    ]
    if partial:
        lines += [
            "<!-- PARTIAL: control-plane allow-list unavailable — regenerate with the "
            "full fleet before trusting this view. -->",
            "",
            "> **PARTIAL VIEW.** The control-plane allow-list was unavailable at",
            "> generation time. This inventory is incomplete; do not rely on it.",
            "",
        ]
    lines += [
        "Read-only view of the `jolarca-dev` fleet, generated from the control-plane",
        "allow-list. The allow-list **remains** the authoritative asset inventory",
        "(ISO 27001 A.5.9 / SOC 2 CC9.2); this page asserts coherence with it and",
        "claims no ownership. `scripts/verify.py` re-checks the count below against",
        "the live allow-list.",
        "",
        f"Repository count: {len(entries)}",
        "",
        "| Repository | Tier | Criticality | Launch status | Visibility "
        "| Classification | Frameworks |",
        "|---|---|---|---|---|---|---|",
    ]
    for e in sorted(entries, key=lambda r: r.name):
        lines.append(
            f"| `{e.name}` | {e.tier} | {e.criticality} | {e.launch_status} "
            f"| {e.visibility} | {e.data_classification} | {e.frameworks} |"
        )
    lines.append("")
    return "\n".join(lines)


def build(control_repos: Path, *, strict: bool) -> tuple[str, list[str]]:
    """Return (markdown, hard_errors)."""
    errors: list[str] = []
    if not control_repos.is_dir():
        if strict:
            errors.append(f"--strict: control-plane allow-list not found at {control_repos}")
            return "", errors
        return render([], partial=True), errors
    entries = load_allowlist(control_repos)
    if not entries:
        errors.append(f"allow-list at {control_repos} produced zero entries")
        return "", errors
    actual = len(list(control_repos.glob("*.yml")))
    if actual != len(entries):
        errors.append(
            f"allow-list coherence: {actual} *.yml files but {len(entries)} parsed entries"
        )
    return render(entries, partial=False), errors


def main(argv: list[str]) -> int:
    strict = "--strict" in argv
    markdown, errors = build(CONTROL_REPOS, strict=strict)
    if errors:
        for err in errors:
            print(f"build_inventory: HARD FAIL: {err}", file=sys.stderr)
        return 1
    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text(markdown, encoding="utf-8")
    print(f"build_inventory: wrote {OUTPUT_MD.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
